### PR TITLE
fix broken markdown

### PR DESCRIPTION
**Pull request by yukihigasi**

### CODE REVIEW

**Comment by ultraq** [comment]
Looks good to me 👍 

@danielfernandez, does this mean we've got busted markdown in all our repos, given that this file is a copy from elsewhere?  Here I think: https://github.com/thymeleaf/thymeleaf-dist/blob/master/CONTRIBUTING.markdown

**Comment by danielfernandez** [comment]
Yes, that is something we have everywhere I'm afraid :(

**Comment by ultraq** [comment]
Merge this and then copy/paste everywhere?

**Comment by danielfernandez** [comment]
Yes. Is it something you could do, at least for some repositories?

**Comment by ultraq** [comment]
I'll try update them all 😉 

Thanks @yukihigasi for this correction!

**Pull request merged**
