### PR TITLE
Updated thymeleaf version to 2.1.5

### PR DESCRIPTION
**Pull request by briksmith**

### CODE REVIEW

**Comment by ultraq** [comment]
PR has merge conflicts @briksmith.  I think you meant to point this to the `2.1-master` branch though, not the `3.0-master` one, which might explain the conflicts?

**Comment by ultraq** [comment]
Oh, I just realized this PR is from this repository's own `2.1-master` branch into the `3.0-master` branch, which should be kept separate.  The 2.1-master branch is already using Thymeleaf 2.1.5.  Closing.

**Comment by briksmith** [comment]
Sorry for causing a problem.  I was trying to pull to get the code.  I should've cloned/download which I did later.

**Comment by ultraq** [comment]
Ah, it all makes sense now 😃  Good to hear you fixed it and managed to get the latest code then 👍

**Pull request closed without merging**
